trigger:
- dev

pool:
  name: 'shared-pool'
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: '**/Shared.Models.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: BuildAndTest
  displayName: Build and Test
  steps:
  - task: NuGetToolInstaller@1
    displayName: nuget installer
    inputs:
      versionSpec: 
      checkLatest: true
  - task: NuGetCommand@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'
      vstsFeed: '10e497bc-88ca-43c1-a0d0-58e2ee0e0002/e676ce1e-3e98-4b56-a4de-82207de1070c'
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '$(solution)'
  